import turtle
c=turtle.Turtle()
c.width(3)
c.speed(20)
for i in range(100,0,-5):
    c.color("red")
    c.forward(i)
    c.left(90)
    c.color("green")
    c.forward(i)
    c.left(90)
    c.color("yellow")
    c.forward(i)
    c.left(90)
    c.color("blue")
    c.forward(i)    
    c.left(90)  
    c.left(45)
    c.fd(3.5)
    c.right(45)          
